version: '2'
services:

 ssh:
  image: jdeathe/centos-ssh:centos-7
  ports:
   - "2020:22"

 rabbitmq:
  image: marcelmaatkamp/rabbitmq-mqtt-ldap
  restart: always
  hostname: rabbitmq
  environment:
   - RABBITMQ_NODENAME=rabbitmq@rabbitmq
  volumes:
   - rabbitmq:/var/lib/rabbitmq/mnesia

 seneca:
  build: .
  environment:
   - LOG_LEVEL=${LOG_LEVEL}
   - AMQP_URL=amqp://rabbitmq

volumes:
 rabbitmq:
