version: '2'
services:

 rabbitmq:
  image: marcelmaatkamp/rabbitmq-mqtt-ldap
  restart: always
  hostname: rabbitmq
  environment:
   - RABBITMQ_NODENAME=rabbitmq@rabbitmq
  volumes:
   - rabbitmq:/var/lib/rabbitmq/mnesia

 seneca:
  build: .
  environment:
   - AMQP_URL=amqp://rabbitmq
   - AMQP_EXCHANGE=geo
   - AMQP_EXCHANGE_TYPE=fanout
   - AMQP_QUEUE=geo.traccar

volumes:
 rabbitmq:
