version: '2'
services:
 
 redis:
  image: "redis:alpine"

 xcessiv:
  image: reiinakano/xcessiv
  command: bash -c "xcessiv -H redis -P 6379"
  ports:
   - "1994:1994"
  volumes:
   - xcessiv:/XcessivProjects

 samba:
  image: grossws/smbd
  ports:
   - "139:139"
   - "445:445"
  volumes:
   - xcessiv:/data

volumes:
 xcessiv:

