version: '2'
services:

 freeradius:
  image: "marcelmaatkamp/freeradius"
  ports:
   - "1812:1812/udp"
   - "1813:1813"
   - "18120:18120"
  volumes:
   - "./conf/clients.conf:/etc/raddb/clients.conf"
   - "./conf/users:/etc/raddb/users"

 ap:
  image: forcedinductionz/docker-ap
  privileged: true
  network_mode: "host"
  depends_on:
   - freeradius
  environment:
   - INTERFACE=wlx001f1fed5baa
  volumes:
   - "./conf/hostapd.conf:/etc/hostapd.conf"
