version: "2"
services:

 https:
  image: steveltn/https-portal
  ports:
   - "80:80"
   - "443:443"
  links:
   - rabbitmq
  restart: always
  volumes:
    - https:/var/lib/https-portal
    - https:/var/www/vhosts
  environment:
#   - STAGE=local
    - STAGE=production
    - DOMAINS=rabbitmq.${IP_ADDRESS}.pseudo.host -> http://rabbitmq:15672

 rabbitmq:
  image: marcelmaatkamp/rabbitmq-mqtt-ldap
  restart: always
  hostname: rabbitmq
  ports:
   - 5671:5671
  environment:
   - RABBITMQ_NODENAME=rabbitmq@rabbitmq
  volumes:
   - ./conf/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
   - rabbitmq:/var/lib/rabbitmq/mnesia
   - https:/var/lib/https

volumes:
 rabbitmq:
 https:
