version: '2'

services:

 thingsboard:
  build:
   context: .
   dockerfile: Dockerfile.run
  image: anapsix/alpine-java
  # command: bash -c 'cd /thingsboard/application && java -jar thingsboard-1.1.0-SNAPSHOT-boot.jar'
  env_file:
   - ./thingsboard/docker/thingsboard.env
  environment:
   - MQTT_START_LOCAL_SERVER=false
   - MQTT_BIND_ADDRESS=rabbitmq
  entrypoint: ./run_thingsboard.sh
  volumes:
   - ./cache/application:/thingsboard/application
   - ./cache/log:/var/log/thingsboard/
  ports:  
   - "8090:8080"
   - "1884:1883"
   - "5683:5683"
  external_links:
   - thingsboard_db_1:db
  
 zk:
  image: "zookeeper:3.4.9"
  restart: always

 rabbitmq:
  image: marcelmaatkamp/rabbitmq-mqtt-ldap
  restart: always
  hostname: rabbitmq
  environment:
   - RABBITMQ_NODENAME=rabbitmq
  volumes:
   - rabbitmq:/var/lib/rabbitmq/
  ports: 
   - 15673:15672
   - 1883:1883

volumes:
 rabbitmq:
