version: '2'

services:
 
 thingsboard:
  build: .
  # command: bash -c 'cd /thingsboard && mvn package -pl application -am -Dmaven.test.skip=true'
  command: bash -c 'cd /thingsboard && mvn package'
  volumes:
   - ./cache/m2:/root/.m2
   - ./cache/npm:/root/.npm
   - ./cache/gradle:/root/.gradle
   - ./cache/application:/thingsboard/application
   - ./thingsboard:/thingsboard

 rabbitmq:
  image: marcelmaatkamp/rabbitmq-mqtt-ldap
  ports: 
   - 15672:15672
   - 1883:1883
